/* eslint-disable object-shorthand */
/* eslint-disable prefer-template */
const Joi = require('joi');

exports.GetConnectionList = async (ctx) => {
  console.log('root GetConnectionList');
  try {
    ctx.body = {
      Success: true,
      Connections: [
        {
          ConnectionName: 'odbc connection',
          ConnectionType: 'ODBC',
          ConnectionString: 'DSN=agensgraph',
          Initializer: 'SET GRAPH_PATH TO GRAPH',
          SequenceTable: '',
          Opaque: {
            opaque: '111'
          }
        }
      ]
    };
  } catch (e) {
    ctx.throw(500, e);
  }
};

exports.GetSchemaList = async (ctx) => {
  const { ConnectionName } = ctx.params;
  console.log('ctx.params', ctx.params);
  console.log('root GetSchemaList', ConnectionName);
  try {
    ctx.body = {
      Success: true,
      ConnectionName: 'odbc connection',
      Tables: [{
        CatalogName: 'catalog',
        SchemaName: 'public',
        TableName: 't1',
        TableType: 'Table',
        SequenceColumn: '',
        Opaque: {
          opaque: '111'
        }
      }]
    };
  } catch (e) {
    ctx.throw(500, e);
  }
};

exports.AddSchema = async (ctx) => {
  const { ConnectionName } = ctx.params;
  console.log('ctx.params', ctx.params);
  console.log('root AddSchema', ConnectionName);
  try {
    ctx.body = {
      Success: true
    };
  } catch (e) {
    ctx.throw(500, e);
  }
};

exports.GetSchema = async (ctx) => {
  const { ConnectionName } = ctx.params;
  console.log('ctx.params', ctx.params);
  console.log('root GetSchema', ConnectionName);
  try {
    ctx.body = {
        "Success": true,
        "ConnectionName": "oracle connection",
        "CatalogName": "catalog",
        "SchemaName": "public",
        "TableName": "t1",
        "TableType": "Table",
        "Columns": [{
            "ColumnName": "c1",
            "Expression": "",
            "ColumnType": "integer",
            "ColumnSize": 0,
            "DecimalDigit": 0
        }, {
            "ColumnName": "c2",
            "Expression": "",
            "ColumnType": "text",
            "ColumnSize": 8190,
            "DecimalDigit": 0
        }],
        "SequenceColumn": "",
        "Opaque": {
            "opaque": "111"
        }
    };
  } catch (e) {
    ctx.throw(500, e);
  }
};

exports.GetModelList = async (ctx) => {
    console.log('root GetModelList');
    const { ConnectionName } = ctx.params;
    console.log('ctx.params', ctx.params);
    try {
      ctx.body = {
        "Success": true,
        "Models": [
                {
                    "ModelName": "model1",
                    "Summery": {
                        "Summery": ""
                    }
                },
                {
                    "ModelName": "model2",
                    "Summery": {
                        "Summery": ""
                    }
                }
            ]
        };
    } catch (e) {
      ctx.throw(500, e);
    }
  };

exports.CollectSchema = async (ctx) => {
  const { ConnectionName } = ctx.params;
  console.log('root CollectSchema', ConnectionName);
  try {
    ctx.body = {
      "Success": true,
      "ConnectionName": "pg connection",
      "Tables": [{
          "CatalogName": "jhkim",
          "SchemaName": "graph",
          "TableName": "ag_edge",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "id",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "start",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "end",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "properties",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "graph",
          "TableName": "ag_vertex",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "id",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "properties",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "network",
          "TableName": "ag_edge",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "id",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "start",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "end",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "properties",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "network",
          "TableName": "ag_vertex",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "id",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "properties",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "network",
          "TableName": "city",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "id",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "properties",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "network",
          "TableName": "customer",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "id",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "properties",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "network",
          "TableName": "dev",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "id",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "properties",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "network",
          "TableName": "knows",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "id",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "start",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "end",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "properties",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "network",
          "TableName": "movie",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "id",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "properties",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "network",
          "TableName": "person",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "id",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "properties",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "audits",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "audit_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "service_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "role_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "created_instant",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "message",
              "ColumnType": "text",
              "ColumnSize": 1048576,
              "DecimalDigit": 0
          }, {
              "ColumnName": "acting_user_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "command_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "user_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "host_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "audit_type",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "config_container_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "cluster_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "host_template_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "ip_address",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "allowed",
              "ColumnType": "text",
              "ColumnSize": 5,
              "DecimalDigit": 0
          }, {
              "ColumnName": "external_account_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "auth_roles",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "auth_role_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "uuid",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "base_role_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "auth_roles_scopes",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "auth_role_scope_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "auth_role_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "scope_cluster_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "client_configs",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "client_config_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "created_instant",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "service_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "config_archive",
              "ColumnType": "binary",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "mime_type",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "filename",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "config_staleness_status",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "metadata",
              "ColumnType": "text",
              "ColumnSize": 8190,
              "DecimalDigit": 0
          }, {
              "ColumnName": "gateway_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "cluster_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "generation",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "resources",
              "ColumnType": "text",
              "ColumnSize": 8190,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "client_configs_to_hosts",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "client_config_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "host_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "cluster_activated_releases",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "cluster_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "release_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "cluster_activated_releases_aud",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "cluster_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "release_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "rev",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "revtype",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "cluster_managed_releases",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "cluster_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "release_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "cluster_undistributed_releases",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "cluster_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "release_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "clusters",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "cluster_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "maintenance_count",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "cdh_version",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "display_name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "uuid",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "data_context_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "cluster_type",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "clusters_aud",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "cluster_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "rev",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "revtype",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "cdh_version",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "display_name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "cm_peers",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "peer_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "url",
              "ColumnType": "text",
              "ColumnSize": 256,
              "DecimalDigit": 0
          }, {
              "ColumnName": "username",
              "ColumnType": "text",
              "ColumnSize": 256,
              "DecimalDigit": 0
          }, {
              "ColumnName": "password",
              "ColumnType": "text",
              "ColumnSize": 256,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "peer_type",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "created_remote_user",
              "ColumnType": "text",
              "ColumnSize": 5,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "cm_version",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "version",
              "ColumnType": "text",
              "ColumnSize": 256,
              "DecimalDigit": 0
          }, {
              "ColumnName": "guid",
              "ColumnType": "text",
              "ColumnSize": 36,
              "DecimalDigit": 0
          }, {
              "ColumnName": "last_update_instant",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "ts",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "hostname",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "last_active_timestamp",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "command_schedules",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "spec_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "command_name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "command_arguments",
              "ColumnType": "text",
              "ColumnSize": 1048576,
              "DecimalDigit": 0
          }, {
              "ColumnName": "cluster_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "service_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "role_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "host_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "start_time",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "end_time",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "repeat_interval",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "repeat_interval_unit",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "paused",
              "ColumnType": "text",
              "ColumnSize": 5,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "fire_after_time",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "display_name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "description",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "commands",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "command_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "state",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "start_instant",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "end_instant",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "active",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "result_message",
              "ColumnType": "text",
              "ColumnSize": 1048576,
              "DecimalDigit": 0
          }, {
              "ColumnName": "result_data",
              "ColumnType": "binary",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "result_data_mime_type",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "result_data_filename",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "success",
              "ColumnType": "text",
              "ColumnSize": 5,
              "DecimalDigit": 0
          }, {
              "ColumnName": "service_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "role_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "parent_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "host_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "result_data_path",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "result_data_reaped",
              "ColumnType": "text",
              "ColumnSize": 5,
              "DecimalDigit": 0
          }, {
              "ColumnName": "cluster_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "schedule_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "arguments",
              "ColumnType": "text",
              "ColumnSize": 1048576,
              "DecimalDigit": 0
          }, {
              "ColumnName": "audited",
              "ColumnType": "text",
              "ColumnSize": 5,
              "DecimalDigit": 0
          }, {
              "ColumnName": "first_updated_instant",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "creation_instant",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "commands_detail",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "command_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "internal_state",
              "ColumnType": "binary",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "comments_profile",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "creationdate",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "locationip",
              "ColumnType": "text",
              "ColumnSize": 80,
              "DecimalDigit": 0
          }, {
              "ColumnName": "browserused",
              "ColumnType": "text",
              "ColumnSize": 80,
              "DecimalDigit": 0
          }, {
              "ColumnName": "content",
              "ColumnType": "text",
              "ColumnSize": 2000,
              "DecimalDigit": 0
          }, {
              "ColumnName": "length",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "config_containers",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "config_container_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "config_type",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "config_generation",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "configs",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "config_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "role_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "attr",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "value",
              "ColumnType": "text",
              "ColumnSize": 1048576,
              "DecimalDigit": 0
          }, {
              "ColumnName": "service_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "host_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "config_container_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "role_config_group_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "context",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "external_account_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "configs_aud",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "config_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "rev",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "revtype",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "attr",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "value",
              "ColumnType": "text",
              "ColumnSize": 1048576,
              "DecimalDigit": 0
          }, {
              "ColumnName": "role_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "role_config_group_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "service_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "host_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "config_container_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "external_account_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "credentials",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "credential_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "principal",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "keytab",
              "ColumnType": "binary",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "data_context_to_base_service",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "data_context_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "service_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "data_contexts",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "data_context_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "uuid",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "display_name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "nameservice",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "created_instant",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "last_modified_instant",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "diagnostics_events",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "event_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "event_name",
              "ColumnType": "text",
              "ColumnSize": 64,
              "DecimalDigit": 0
          }, {
              "ColumnName": "event_type",
              "ColumnType": "text",
              "ColumnSize": 32,
              "DecimalDigit": 0
          }, {
              "ColumnName": "event_time",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "details",
              "ColumnType": "text",
              "ColumnSize": 8190,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "external_accounts",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "external_account_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "type_name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "display_name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "created_instant",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "last_modified_instant",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "external_accounts_aud",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "external_account_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "rev",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "revtype",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "type_name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "display_name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "created_instant",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "last_modified_instant",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "external_mapping_auth_roles",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "external_mapping_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "auth_role_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "external_mappings",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "external_mapping_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "uuid",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "code",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "external_mapping_type",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "global_settings",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "global_setting_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "attr",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "value",
              "ColumnType": "text",
              "ColumnSize": 1048576,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "history",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "year",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "event",
              "ColumnType": "text",
              "ColumnSize": 8190,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "host_template_to_role_conf_grp",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "host_template_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "role_config_group_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "host_templates",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "host_template_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "cluster_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "hosts",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "host_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "host_identifier",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "ip_address",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "rack_id",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "status",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "config_container_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "maintenance_count",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "decommission_count",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "cluster_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "num_cores",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "total_phys_mem_bytes",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "public_name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "public_ip_address",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "cloud_provider",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "hosts_aud",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "host_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "rev",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "revtype",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "host_identifier",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "cluster_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "config_container_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "metrics",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "metric_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "metric_identifier",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "metric",
              "ColumnType": "text",
              "ColumnSize": 1048576,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "parcel_components",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "parcel_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "version",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "component_name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "parcels",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "parcel_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "product",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "version",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "os",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "filename",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "hash",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "binary_diff",
              "ColumnType": "text",
              "ColumnSize": 5,
              "DecimalDigit": 0
          }, {
              "ColumnName": "status",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "source",
              "ColumnType": "text",
              "ColumnSize": 4000,
              "DecimalDigit": 0
          }, {
              "ColumnName": "release_instant",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "download_instant",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "release_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "pg_stat_statements",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "userid",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "dbid",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "queryid",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "query",
              "ColumnType": "text",
              "ColumnSize": 8190,
              "DecimalDigit": 0
          }, {
              "ColumnName": "calls",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "total_time",
              "ColumnType": "float",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "min_time",
              "ColumnType": "float",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "max_time",
              "ColumnType": "float",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "mean_time",
              "ColumnType": "float",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "stddev_time",
              "ColumnType": "float",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "rows",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "shared_blks_hit",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "shared_blks_read",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "shared_blks_dirtied",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "shared_blks_written",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "local_blks_hit",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "local_blks_read",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "local_blks_dirtied",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "local_blks_written",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "temp_blks_read",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "temp_blks_written",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "blk_read_time",
              "ColumnType": "float",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "blk_write_time",
              "ColumnType": "float",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "process_active_releases",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "process_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "release_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "processes",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "process_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "role_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "command_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "host_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "process_user",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "process_group",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "program",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "arguments",
              "ColumnType": "text",
              "ColumnSize": 1048576,
              "DecimalDigit": 0
          }, {
              "ColumnName": "running",
              "ColumnType": "text",
              "ColumnSize": 5,
              "DecimalDigit": 0
          }, {
              "ColumnName": "run_generation",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "one_off",
              "ColumnType": "text",
              "ColumnSize": 5,
              "DecimalDigit": 0
          }, {
              "ColumnName": "status_links",
              "ColumnType": "text",
              "ColumnSize": 1048576,
              "DecimalDigit": 0
          }, {
              "ColumnName": "resources",
              "ColumnType": "text",
              "ColumnSize": 8190,
              "DecimalDigit": 0
          }, {
              "ColumnName": "environment",
              "ColumnType": "text",
              "ColumnSize": 8190,
              "DecimalDigit": 0
          }, {
              "ColumnName": "created_instant",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "special_file_info",
              "ColumnType": "text",
              "ColumnSize": 8190,
              "DecimalDigit": 0
          }, {
              "ColumnName": "auto_restart",
              "ColumnType": "text",
              "ColumnSize": 5,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "updated_instant",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "required_parcel_tags",
              "ColumnType": "text",
              "ColumnSize": 8190,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optional_parcel_tags",
              "ColumnType": "text",
              "ColumnSize": 8190,
              "DecimalDigit": 0
          }, {
              "ColumnName": "config_generation",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "extra_groups",
              "ColumnType": "text",
              "ColumnSize": 8190,
              "DecimalDigit": 0
          }, {
              "ColumnName": "start_secs",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "exit_codes",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "processes_detail",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "process_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "configuration_data",
              "ColumnType": "binary",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "refresh_files",
              "ColumnType": "text",
              "ColumnSize": 1048576,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "releases",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "release_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "product",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "version",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "release_notes",
              "ColumnType": "text",
              "ColumnSize": 8190,
              "DecimalDigit": 0
          }, {
              "ColumnName": "depends",
              "ColumnType": "text",
              "ColumnSize": 8190,
              "DecimalDigit": 0
          }, {
              "ColumnName": "conflicts",
              "ColumnType": "text",
              "ColumnSize": 8190,
              "DecimalDigit": 0
          }, {
              "ColumnName": "replaces",
              "ColumnType": "text",
              "ColumnSize": 8190,
              "DecimalDigit": 0
          }, {
              "ColumnName": "services_restart_info",
              "ColumnType": "text",
              "ColumnSize": 8190,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "releases_aud",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "release_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "rev",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "revtype",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "product",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "version",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "revisions",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "revision_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "user_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "timestamp",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "message",
              "ColumnType": "text",
              "ColumnSize": 1048576,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "role_config_groups",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "role_config_group_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "role_type",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "base",
              "ColumnType": "text",
              "ColumnSize": 5,
              "DecimalDigit": 0
          }, {
              "ColumnName": "display_name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "service_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "role_config_groups_aud",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "role_config_group_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "rev",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "revtype",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "role_type",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "display_name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "base",
              "ColumnType": "text",
              "ColumnSize": 5,
              "DecimalDigit": 0
          }, {
              "ColumnName": "service_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "role_staleness_status",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "role_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "status",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "roles",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "role_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "host_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "role_type",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "configured_status",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "service_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "merged_keytab",
              "ColumnType": "binary",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "maintenance_count",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "decommission_count",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "role_config_group_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "has_ever_started",
              "ColumnType": "text",
              "ColumnSize": 5,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "roles_aud",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "role_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "rev",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "revtype",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "role_type",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "host_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "service_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "role_config_group_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "schema_version",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "old_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "services",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "service_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "service_type",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "cluster_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "maintenance_count",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "display_name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "generation",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "services_aud",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "service_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "rev",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "revtype",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "service_type",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "cluster_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "display_name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "snapshot_policies",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "policy_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "policy_identifier",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "description",
              "ColumnType": "text",
              "ColumnSize": 1048576,
              "DecimalDigit": 0
          }, {
              "ColumnName": "service_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "schedule_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "hourly_snapshots",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "daily_snapshots",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "weekly_snapshots",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "monthly_snapshots",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "yearly_snapshots",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "minute_of_hour",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "hour_of_day",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "day_of_week",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "day_of_month",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "month_of_year",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "hours_list",
              "ColumnType": "text",
              "ColumnSize": 1048576,
              "DecimalDigit": 0
          }, {
              "ColumnName": "entities_to_snapshot",
              "ColumnType": "text",
              "ColumnSize": 1048576,
              "DecimalDigit": 0
          }, {
              "ColumnName": "alert_on_start",
              "ColumnType": "text",
              "ColumnSize": 5,
              "DecimalDigit": 0
          }, {
              "ColumnName": "alert_on_success",
              "ColumnType": "text",
              "ColumnSize": 5,
              "DecimalDigit": 0
          }, {
              "ColumnName": "alert_on_fail",
              "ColumnType": "text",
              "ColumnSize": 5,
              "DecimalDigit": 0
          }, {
              "ColumnName": "alert_on_abort",
              "ColumnType": "text",
              "ColumnSize": 5,
              "DecimalDigit": 0
          }, {
              "ColumnName": "paused",
              "ColumnType": "text",
              "ColumnSize": 5,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "user_auth_roles",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "user_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "auth_role_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "user_roles",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "user_role_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "user_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "user_role",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "user_settings",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "user_setting_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "user_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "attr",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "value",
              "ColumnType": "text",
              "ColumnSize": 1048576,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }, {
          "CatalogName": "jhkim",
          "SchemaName": "public",
          "TableName": "users",
          "TableType": "Table",
          "Columns": [{
              "ColumnName": "user_id",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "user_name",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "password_hash",
              "ColumnType": "text",
              "ColumnSize": 255,
              "DecimalDigit": 0
          }, {
              "ColumnName": "password_salt",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }, {
              "ColumnName": "password_login",
              "ColumnType": "text",
              "ColumnSize": 5,
              "DecimalDigit": 0
          }, {
              "ColumnName": "optimistic_lock_version",
              "ColumnType": "integer",
              "ColumnSize": 0,
              "DecimalDigit": 0
          }]
      }]
  };
  } catch (e) {
    ctx.throw(500, e);
  }
};